# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
    dockerRegistry: gcrServiceConnection
    DOCKER_REGISTRY: 'us.gcr.io/wiz-builder/'
pool:
  vmImage: 'ubuntu-latest'

steps:
- powershell: Copy-Item .\deployment.yml $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'

- task: DockerCompose@0
  displayName: Build services
  inputs:
    action: Build services
    containerregistrytype: Container Registry
    dockerRegistryEndpoint: $(dockerRegistry)
    dockerComposeFile: docker-compose.yml
    projectName: $(Build.Repository.Name)
    qualifyImageNames: true

- task: DotNetCoreCLI@2
  displayName: Unit tests
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DockerCompose@0
  displayName: Push services
  inputs:
    action: Push services
    containerregistrytype: Container Registry
    dockerRegistryEndpoint: $(dockerRegistry)
    dockerComposeFile: docker-compose.yml
    projectName: $(Build.Repository.Name)
    qualifyImageNames: true
